version: "3.8"
services:
  flyway:
    image: flyway/flyway
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf
      - ./keys:/flyway/keys
    command: migrate -url="jdbc:snowflake://mechanicalrock.ap-southeast-2.snowflakecomputing.com/?db=pipeline_db_migration_plan&warehouse=pipeline_warehouse&role=pipeline_role&user=pipeline_sys_user&authenticator=snowflake_jwt&private_key_file=/flyway/keys/rsa_key.p8"

  snowflake:
      build:
          context: .
          dockerfile: Dockerfile
      volumes:
        - ./sql:/flyway/sql
        - ./conf:/flyway/conf
        - ./keys:/flyway/keys
      command: migrate -url="jdbc:snowflake://mechanicalrock.ap-southeast-2.snowflakecomputing.com/?db=pipeline_db_migration_plan&warehouse=pipeline_warehouse&role=pipeline_role&user=pipeline_temp_user&password=${SNOWFLAKE_PASSWORD}"
