version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
    commands:
      - export SNOWFLAKE_PASSWORD=$(aws secretsmanager get-secret-value --secret-id snowflake/$SNOWFLAKE_USER --query SecretString --output text)
      - apt-get update && apt-get install jq -y --no-install-recommends

  build:
    commands:
      - ls -la
      - pwd
      - flyway migrate -url="jdbc:snowflake://${SnowflakeAccount}.snowflakecomputing.com/?db=${SnowflakeMigrationDatabaseName}&warehouse=${SnowflakeWarehouse}&role=${SnowflakeRole}&user=${SNOWFLAKE_USER}&password=${SNOWFLAKE_PASSWORD}"
